### ISSUE TITLE
 helm install cert-manager with errors

### ISSUE THREAD

**Issue by Nodewebzsz** [cert-manager/website#1255]
helm install cert-manager jetstack/cert-manager --version v1.11.1   
<img width="1166" alt="image" src="https://github.com/cert-manager/website/assets/23263051/50429c28-77f5-4709-bff8-eeb1b14ab48b">

**Comment by hawksight** [comment]
I just tried this and it worked for me in a fresh cluster. Usually something like this might be because your machine is part of a corporate network and the traffic might be going via a proxy? Could that be the case here.

Does this command work for you now?

If not, can you do the following and paste the output?

```shell
helm repo ls
```

**Comment by inteon** [comment]
This could be a proxy issue or a temporary hosting issue.
Anyway, the issue is not present currently.
