### ISSUE TITLE
Documentation on how to handle large-scale certificate management & best practices

### ISSUE THREAD

**Issue by rauny-brandao** [cert-manager/website#551]
**Is your feature request related to a problem? Please describe.**

I would like to know what are the best practices for handling large-scale certificate management.
Currently I have almost 20k certificates in the following setup:

1. cert-manager installed in an EKS cluster
2. ClusterIssuer generating ACME certificates
3. Kubernetes objects stored in a single namespace (Ingress, Certificate, CertificateRequest, Order and Challenge)
4. 2 replicas of each pod (controller, ca-injector and webhook)

I'm concerned about the issues that will occur when I hit 5, 10x the current workload (200k certificates).
What are the best practices for handling this usage?

**Describe the solution you'd like**

A section added to the documentation on how to handle large-scale certificate management with cert-manager

**Describe alternatives you've considered**

After reading this [https://github.com/jetstack/cert-manager/issues/3748](https://github.com/jetstack/cert-manager/issues/3748) I'm considering splitting in multiple clusters once a certain number of certificates are created, 20k certificates in this case.

Another possible solution is: single-namespace deployments for handling a certain number of certificates: [https://github.com/jetstack/cert-manager/issues/2525](https://github.com/jetstack/cert-manager/issues/2525), but I'm still not sure about this.

**Environment details**:
- Kubernetes version: v1.19
- Cloud-provider/provisioner: AWS EKS
- cert-manager version: 1.3.1
- Install method: helm

/kind documentation

**Comment by raunyoliveira-hotmart** [comment]
Reference [https://github.com/jetstack/cert-manager/issues/3971#issuecomment-833359974](https://github.com/jetstack/cert-manager/issues/3971#issuecomment-833359974)

**Comment by irbekrm** [comment]
Thanks for opening the issue!

We could start a doc with best practices for running large-scale `cert-manager` deployments.

I'm adding a `help-wanted` label for the issue- any user input would be very much appreaciated 🙏🏼

**Comment by raunyoliveira-hotmart** [comment]
@irbekrm update about our use case:

1. cert-manager version 1.6.1 installed with helm on EKS
2. ClusterIssuer generating ACME certificates
3. Kubernetes objects stored in a single namespace (Ingress, Certificate, CertificateRequest, Order and Challenge)
4. 2 replicas of each pod (controller, ca-injector and webhook)

this current setup is handling 80k+ certificates, but with some issues:

1. had to create a separate process/script to check if the certificate can be renewed, and remove it if not, before auto renew from cert-manager is triggered
2. running kubectl commands on the namespace takes a long time or doesn't work at all

**Comment by wallrj** [comment]
We did not get round to writing this guide during the Season of Docs 2022, but if someone here would like to contribute a PR I will be happy to review. Pester me in #cert-manager-dev on Slack.

I have recently started an [Installation > Best Practice](https://cert-manager.io/docs/installation/best-practice/) document.
We could add a section to that document explaining some recommended changes to the command line flags of the components.

And I can imagine a Configuration > Best Practice document which could be as simple as a list of Certificate and Issuer configuration parameters which we recommend.

This is somewhat related to the sane defaults issue:
 * https://github.com/cert-manager/cert-manager/issues/3958

And it is worth noting that @irbekrm has radically reduced the memory consumption of cert-manager components on clusters with large numbers of Secrets and with large Secret data.
 * https://cert-manager.io/docs/release-notes/release-notes-1.10#v1102-changes-since-v1101
 * https://cert-manager.io/docs/release-notes/release-notes-1.11
