### ISSUE TITLE
Route53: document use of "region" field

### ISSUE THREAD

**Issue by stephen-dexda** [cert-manager/website#56]
The Route53 [docs](https://cert-manager.io/docs/configuration/acme/dns01/route53/) and [API reference](https://cert-manager.io/docs/reference/api-docs/#acme.cert-manager.io/v1alpha2.ACMEIssuerDNS01ProviderRoute53) list a region field for the route53 solver, with the latter saying "Always set the region when using AccessKeyID and SecretAccessKey".

It's not clear what the value of this should correspond to, since IAM users and access keys are not associated with a region?

**Comment by TBBle** [comment]
Looking at [the source](https://github.com/jetstack/cert-manager/blob/master/pkg/issuer/acme/dns/route53/route53.go), it's actually _not_ needed if you are using ambient credentials, e.g. a Service Account with appropriate IAMs Role; it will happily take and ignore an empty string in this case, which should use the ambient credential's region anywhere that's needed.

However, the CRD rejects that, so I couldn't test that it actually works, or if AWS actually always requires an explicit region here for some reason.

**Comment by TBBle** [comment]
Looking at https://github.com/jetstack/cert-manager/pull/1917, it appears region's "requiredness" persisted from when the credentials were mandatory. That's probably what the comment meant?

**Comment by wallrj** [comment]
@stephen-dexda @TBBle Thanks for reporting and commenting on this. It's been a long time, but if either of you have time to improve the documentation, please create a PR and find me on #cert-manager-dev in Slack for code review.

**Comment by TBBle** [comment]
I'm not in a position to put up PRs, but I'll just highlight that although this bug was filed on the website repo, I think it's actually revealed a bug in the Issuer/ClusterIssuer CRDs themselves that the `region` field is required, which (if I understand my own earlier comment correctly) blocks the empty string value that [the code](https://github.com/cert-manager/cert-manager/blob/master/pkg/issuer/acme/dns/route53/route53.go) is correctly set up to handle.

So right now, a documentation update would have to be "Region is required, and must be provided even if both `accessKeyID` and `accessKeyIDSecretRef` are not provided."

Per https://docs.aws.amazon.com/general/latest/gr/r53.html (to answer the original question) it apparently needs to be `us-east-1` or in some cases `cn-northwest-1`. (It's been literally years and I'm no longer in that job so can't check, so perhaps it works no matter what region you specify, or perhaps I already used `us-east-1` here but for unrelated reasons; I don't think I knew about this page before).

That AWS doc also suggests that leaving the region and endpoint empty in the request would be valid too, so perhaps that field should just be dropped entirely, unless there's a need for manually-specified region elsewhere in the Route53 DNS-01 implementation that I'm overlooking.

**Comment by wallrj** [comment]
A beta-release is now available which contains the fix for this issue. Please test and feedback if you have time.
* https://github.com/cert-manager/cert-manager/releases/tag/v1.16.0-beta.0
