### ISSUE TITLE
New website design is too narrow

### ISSUE THREAD

**Issue by tznamena** [cert-manager/website#913]
New design is nice looking(colors, fonts, etc.) but makes website less usable! 

The site is full of technical information and it is all squished to a narrow column now and everything requires scrolling!

The menu on the side is too narrow and in many cases does not fit the content.

The code examples do not fit the narrow columns!

In short, although nice, it is less usable.

Notice the word "Introduction" in the DNS01 level does not fit anymore!
![Screenshot from 2022-04-13 14-44-13](https://user-images.githubusercontent.com/93541722/163249541-dbaff1aa-8bf9-4410-8485-afb6cfa872b3.png)

Notice all code examples now have horizontal scroll bars. Absolute worse when you try to get some information from a site.
![Screenshot from 2022-04-13 14-48-03](https://user-images.githubusercontent.com/93541722/163249719-b59d8312-5482-4ec5-813a-33f0331fbbbe.png)

**Comment by SgtCoDFish** [comment]
Thanks for raising this issue. I totally understand what you're saying. I'm sure we'll iterate on the design over time.

The website refresh has been a long piece of work for many reasons, and it's still a work in progress.

Gonna close this because we're very aware of this, but thank you again for raising!
